#!/bin/bash

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

#twm &
#exec awesome
xsetroot -cursor_name left_ptr
xmonad &
xmobar &
exec gnome-session &
#xclock -geometry 50x50-1+1 &
#xterm -geometry 80x50+494+51 &
#xterm -geometry 80x20+494-0 &
#exec xterm -geometry 80x66+0+0 -name login

# set the xrand multi desktop
ifconfig | grep 164.99 # check if office or home
test "x$?" = "x1" && home=1
xrandr | grep VGA1 && (xrandr --output VGA1 --auto && xrandr --output VGA1 --primary $(test "x$home" = "x1" && echo -n "--left-of" || echo -n "--right-of") LVDS1) 
xrandr | grep VGA2 && (xrandr --output VGA2 --auto && xrandr --output VGA2 --primary $(test "x$home" = "x1" && echo -n "--left-of" || echo -n "--right-of") LVDS2)

# start some programs
cairo-clock &
emacs &
gnome-screensaver &
exec rxvt 
